kind: PersistentVolume
apiVersion: v1
metadata:
  name: web-push
  namespace: samples-web-push
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/web-push/nginx"