kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-push
  namespace: samples-web-push
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi