kind: PersistentVolume
apiVersion: v1
metadata:
  name: app-sync
  namespace: samples-app-sync
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/app-sync/nginx"