kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-sync
  namespace: samples-app-sync
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi